//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTracNghiemOnline.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.Answers = new HashSet<Answer>();
        }
    
        public int ID_Quiz { get; set; }
        [DisplayName("Câu")]
        public int ID_Question { get; set; }
        [DisplayName("Nội dung")]
        public string Content_of_Question { get; set; }
        [DisplayName("Loại")]
        public Nullable<int> Type_of_Question { get; set; }
        [DisplayName("Điểm")]
        public Nullable<double> Score { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual Quiz Quiz { get; set; }
        public virtual Type_of_Question Type_of_Question1 { get; set; }
    }
}
